import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import CopyRightComponent from "./components/copyright";
import BackToTop from "./components/backtotop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Akeshya",
  description: "this site generated by example",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
          <BackToTop />
        <CopyRightComponent />
      </body>
    </html>
  );
}
